---
title: "CheckingFuntion"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CkeckingFuntion}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(MATH4793CHUProject1)
```

# Project 1

## Test funtion
```{r}
library(MATH4793CHUProject1)

```

### Test univariate Normality by theory
```{r}
theoryUnivNormality(T4_6$V1)
```

### construct a Q-Q plot
```{r}
getQQplot(T4_6$V1)
```

### find the correlation coefficient of the Q-Q plot
```{r}
corQ(T4_6$V1)
```

### test for bivariate Normality
textbook example
```{r}
x <- cbind(sales, profits)
bivNormality(x, alpha=0.5)
```

dataset example
```{r}
x <- cbind(T4_6$V1, T4_6$V2)
bivNormality(x, alpha=0.5)
```

### MVN
textbook example
```{r}
x <- cbind(sales, profits)
testMVN(x)
```

dataset example
```{r}
y <- cbind(T4_6$V1, T4_6$V2, T4_6$V3, T4_6$V4, T4_6$V5)
testMVN(y)
```





## correlation of boxcox plot
```{r}
boxcox(T4_6$V1)
```

